// scripts/type-graph/render.ts
//
// Renders the DSL type graph to Mermaid. Merges the DERIVED structural edges
// (extract.ts -> structural.json) with the HAND-AUTHORED semantic sidecar
// (semantic-edges.json), validates the sidecar endpoints against the real node
// set (the DRIFT GUARD — a stale sidecar endpoint fails here), and emits a
// tier-grouped flowchart.
//
//   structural edges = solid arrows  (composition: A contains/references B)
//   semantic edges    = dashed arrows (shares-shape / shared-atom / dual-nature)
//
// Run: node scripts/type-graph/render.ts <structural.json> <semantic-edges.json>

import { readFileSync } from "node:fs";

interface Node { id: string; tier: 1 | 2 | 3 | 4; kind: string; inDegree: number; outDegree: number; }
interface Edge { from: string; to: string; kind: string; }
interface SemEdge { from: string; to: string; type: string; via?: string; label: string; }

const TIER_TITLE: Record<number, string> = {
  1: "Tier 1 — value atoms",
  2: "Tier 2 — entries / clauses",
  3: "Tier 3 — sub-documents",
  4: "Tier 4 — unit (apex)",
};

function main(): void {
  const structPath = process.argv[2] ?? "scripts/type-graph/structural.json";
  const semPath = process.argv[3] ?? "scripts/type-graph/semantic-edges.json";

  const struct = JSON.parse(readFileSync(structPath, "utf8")) as { nodes: Node[]; edges: Edge[] };
  const sem = JSON.parse(readFileSync(semPath, "utf8")) as { semanticEdges: SemEdge[] };

  const nodeIds = new Set(struct.nodes.map((n) => n.id));

  // --- DRIFT GUARD: every semantic-edge endpoint must be a real node. ---
  const stale: string[] = [];
  for (const e of sem.semanticEdges) {
    if (!nodeIds.has(e.from)) stale.push(`semantic edge from="${e.from}" is not a known type`);
    if (!nodeIds.has(e.to)) stale.push(`semantic edge to="${e.to}" is not a known type`);
  }
  if (stale.length > 0) {
    process.stderr.write("DRIFT: semantic-edges.json references types that no longer exist:\n");
    for (const s of stale) process.stderr.write(`  - ${s}\n`);
    process.exit(1);
  }

  // --- Mermaid ---
  const L: string[] = [];
  L.push("```mermaid");
  L.push("flowchart TD");
  L.push("  %% AUTO-GENERATED by scripts/type-graph/render.ts — DO NOT EDIT BY HAND.");
  L.push("  %% Structural edges (solid) are DERIVED from types/*.ts; semantic edges");
  L.push("  %% (dashed) are from semantic-edges.json. Regenerate after any type change.");
  L.push("");

  // tier subgraphs (node label includes in/out degree so the hub/sink read at a glance)
  for (const tier of [1, 2, 3, 4] as const) {
    const tierNodes = struct.nodes.filter((n) => n.tier === tier);
    L.push(`  subgraph T${tier}["${TIER_TITLE[tier]}"]`);
    for (const n of tierNodes) {
      L.push(`    ${n.id}["${n.id}<br/><small>in ${n.inDegree} · out ${n.outDegree}</small>"]`);
    }
    L.push("  end");
  }
  L.push("");

  // structural edges — solid
  for (const e of struct.edges) {
    L.push(`  ${e.from} --> ${e.to}`);
  }
  L.push("");

  // semantic edges — dashed, labeled with the relationship type (self-loops allowed)
  for (const e of sem.semanticEdges) {
    L.push(`  ${e.from} -. ${e.type} .-> ${e.to}`);
  }
  L.push("");

  // styling: tint by tier kind
  L.push("  classDef value fill:#e8f0fe,stroke:#4285f4;");
  L.push("  classDef entry fill:#e6f4ea,stroke:#34a853;");
  L.push("  classDef subdoc fill:#fef7e0,stroke:#fbbc04;");
  L.push("  classDef unit fill:#fce8e6,stroke:#ea4335;");
  for (const n of struct.nodes) L.push(`  class ${n.id} ${n.kind};`);

  L.push("```");
  process.stdout.write(L.join("\n") + "\n");
}

main();
