// scripts/type-graph/render-keys.ts
//
// Renders the KEY-LEVEL DSL graph (the `_`-keys an author writes) to Mermaid.
// Busier than the type graph (52 nodes), so it groups nodes by their role and
// uses two edge styles:
//   contains   (solid)  — a container key holds a child key
//   member-of  (dashed) — a closed token belongs to an atom's value-set
//
// Run: node scripts/type-graph/render-keys.ts <keys.json>

import { readFileSync } from "node:fs";

interface KeyNode { id: string; group: string; }
interface KeyEdge { from: string; to: string; kind: "contains" | "member-of"; }

const GROUP_TITLE: Record<string, string> = {
  container: "Containers",
  frontmatter: "Phase frontmatter keys",
  "fragment-entry": "_fragments entry sub-keys",
  "guarded-entry": "_knowledge/_templates entry sub-keys",
  reentry: "_re_entry_guard sub-keys",
  "trigger-form": "Trigger forms (closed set)",
  "error-action": "Error actions (closed set)",
  "check-verb": "Check verbs (closed set)",
  meta: "Step meta keys (closed set)",
  condition: "Condition keys",
};
const GROUP_ORDER = ["container", "frontmatter", "fragment-entry", "guarded-entry", "reentry", "trigger-form", "error-action", "check-verb", "meta"];

// Mermaid node ids can't contain leading underscores cleanly in all renderers;
// map each key to a safe alias and keep the real key as the label.
function alias(id: string): string {
  return "k_" + id.replace(/[^A-Za-z0-9]/g, "_");
}

function main(): void {
  const path = process.argv[2] ?? "scripts/type-graph/keys.json";
  const g = JSON.parse(readFileSync(path, "utf8")) as { nodes: KeyNode[]; edges: KeyEdge[] };

  const L: string[] = [];
  L.push("```mermaid");
  L.push("flowchart LR");
  L.push("  %% AUTO-GENERATED by scripts/type-graph/render-keys.ts — DO NOT EDIT BY HAND.");
  L.push("  %% Key-level view: the _-keys an author writes. Closed token sets are");
  L.push("  %% DERIVED from the *_KINDS arrays in types/*.ts. Regenerate after changes.");
  L.push("  %% solid = contains; dashed = member-of (closed value-set).");
  L.push("");

  for (const group of GROUP_ORDER) {
    const ns = g.nodes.filter((n) => n.group === group);
    if (ns.length === 0) continue;
    L.push(`  subgraph G_${group}["${GROUP_TITLE[group] ?? group}"]`);
    for (const n of ns) L.push(`    ${alias(n.id)}["${n.id}"]`);
    L.push("  end");
  }
  L.push("");

  for (const e of g.edges) {
    if (e.kind === "contains") L.push(`  ${alias(e.from)} --> ${alias(e.to)}`);
    else L.push(`  ${alias(e.from)} -. member .-> ${alias(e.to)}`);
  }
  L.push("");

  // tint closed-set tokens vs structural keys
  L.push("  classDef closed fill:#e8f0fe,stroke:#4285f4;");
  L.push("  classDef structural fill:#e6f4ea,stroke:#34a853;");
  L.push("  classDef container fill:#fef7e0,stroke:#fbbc04;");
  for (const n of g.nodes) {
    const cls = n.group === "container" ? "container"
      : ["trigger-form", "error-action", "check-verb", "meta"].includes(n.group) ? "closed"
      : "structural";
    L.push(`  class ${alias(n.id)} ${cls};`);
  }
  L.push("```");
  process.stdout.write(L.join("\n") + "\n");
}

main();
